[package]
name = "dioxus-material"
description = "Animation library for Dioxus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    ".",
    "lookbook"
]

[dependencies]
dioxus = "0.5.0"
dioxus-use-mounted = "0.2.0"
dioxus-spring = { git = "https://github.com/matthunz/dioxus-spring" }
dioxus-resize-observer = "0.2.0"
log = "0.4.20"
dioxus-logger = "0.4.1"
