[package]
name = "dioxus-material"
description = "Animation library for Dioxus"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    ".",
    # "lookbook"
]

[dependencies]
dioxus = "0.5.1"
dioxus-use-mounted = "0.2.1"
dioxus-spring = "0.2.0"
dioxus-resize-observer = "0.2.1"
log = "0.4.22"
dioxus-logger = "0.5.1"

[dev-dependencies]
dioxus = { version = "0.5.1", features = ["web"] }
