[application]
name = "Dioxus Material"
default_platform = "web"

[web.app]
title = "Dioxus Material"
base_path = "dioxus-material/lookbook"

[web.watcher]
reload_html = true

[web.resource]

[web.resource.dev]
